<div class="formWrap">
<?php

 $title = 'Add new bus line';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('line', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('description'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 </div>