<div class="formWrap">
<?php

 $title = 'Add new bus stop';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <?php
 $form->setAttribute('action', $this->url('busstop', array('action' => 'add')));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('lat'));
 echo $this->formRow($form->get('lng'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
 </div>