<div class="formWrap">
<?php
 $title = 'Edit bus stop';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>

 <?php
 $form = $this->form;
 $form->setAttribute('action', $this->url(
     'busstop',
     array(
         'action' => 'edit',
         'slug'     => $this->slug,
     )
 ));
 $form->prepare();

 echo $this->form()->openTag($form);
 echo $this->formHidden($form->get('id'));
 echo $this->formRow($form->get('name'));
 echo $this->formRow($form->get('lat'));
 echo $this->formRow($form->get('lng'));
 echo $this->formSubmit($form->get('submit'));
 echo $this->form()->closeTag();
 ?>
</div>