 <?php
 $title = 'Bus stops';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('busstop', array('action'=>'add'));?>">Add new</a>
 </p>

 <table class="table">
 <tr>
     <th>Name</th>
     <th>Latitude</th>
     <th>Longitude</th>
     <th>&nbsp;</th>
 </tr>
 <?php foreach ($busstops as $busStop) : ?>
 <tr>
     <td><?php echo $this->escapeHtml($busStop->name);?></td>
     <td><?php echo $this->escapeHtml($busStop->lat);?></td>
     <td><?php echo $this->escapeHtml($busStop->lng);?></td>
     <td>
         <a href="<?php echo $this->url('busstop',
             array('action'=>'edit', 'id' => $busStop->id));?>">Edit</a>
         <a href="<?php echo $this->url('busstop',
             array('action'=>'delete', 'id' => $busStop->id));?>">Delete</a>
     </td>
 </tr>
 <?php endforeach; ?>
 </table>